class RPATH_SoftwareInstallationService : CIM_SoftwareInstallationService
{
   [Description ("Repository Address")]
   string RepositoryAddress;

   [Description ("Proxy Server Address")]
   string ProxyServerAddress;

   [Description ("Automatic updates"),
     ValueMap { "0", "1", "2", "3" },
     Values {"No Automatic Updates", "Automatic Check for updates",
        "Automatic Check and Download of updates",
        "Automatic Check, Download & Install of updates"} ]
   uint16 AutomaticUpdates;

   [Description ("Set Repository Address"),
       ValueMap { "0", "1"},
       Values { "OK", "Failed"}]
   uint16 SetRepositoryAddress([in] string RepositoryAddress);

   [Description ("Set Proxy Server Address"),
       ValueMap { "0", "1"},
       Values { "OK", "Failed"}]
   uint16 SetProxyServerAddress([in] string ProxyServerAddress);

   [Description ("Set automatic updates"),
       ValueMap { "0", "1", "2"},
       Values { "OK", "Not Supported", "Failed"}]
   uint16 SetAutomaticUpdates(
        [IN, Description ("Automatic updates setting"),
             ValueMap { "0", "1", "2", "3" },
             Values {"No Automatic Updates", "Automatic Check for updates",
                "Automatic Check and Download of updates",
                "Automatic Check, Download & Install of updates"}]
        uint16 AutomaticUpdates);

    [Description ("Check for updates"),
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "..", "4096",
          "4097", "4098", "4099", "4100", "4101", "4102", "4103",
          "4104", "4105", "4106", "4107", "4108", "4109..32767",
          "32768..65535" },
       Values { "Job Completed with No Error", "Not Supported",
          "Unspecified Error", "Timeout", "Failed",
          "Invalid Parameter", "Target In Use", "DMTF Reserved",
          "Method Parameters Checked - Job Started",
          "Unsupported TargetType",
          "Unattended/silent installation not supported",
          "Downgrade/reinstall not supported", "Not enough memory",
          "Not enough swap-space", "Unsupported version transition",
          "Not enough disk space",
          "Software and target operating system mismatch",
          "Missing dependencies", "Not applicable to target",
          "No supported path to image", "Cannot add to Collection",
          "Method Reserved", "Vendor Specific" }]
   uint32 CheckAvailableUpdates(
         [IN ( false ), OUT, Description (
             "Reference to the job (may be null if job completed)."
              )]
      CIM_ConcreteJob REF Job,
         [IN, Description (
             "Reference to the ManagedElement that the Software "
             "Identity is going to be installed in (or updated)." )]
      CIM_ManagedElement REF Target);

    [Description (
        "Start a job to update or migrate software on a "
        "ManagedElement (Target)."),
     ValueMap { "0"
         },
     Values { "Job Completed with No Error"
         }]
    uint32 InstallFromNetworkLocations(
        [IN ( false ), OUT, Description (
            "Reference to the job (may be null if job completed).")]
        CIM_ConcreteJob REF Job,

        [IN,
            Description("List of management nodes against this system will be registered")]
        string ManagementNodeAddresses[],

        [IN, Description("References to the locations")]
        string Sources[],

        [IN, Description ("The installation target.")]
        CIM_ManagedElement REF Target,

        [IN, Description("Installation options"),
            ValueMap {
                "1", "2", "3", "4"
                },
            Values {
                "Update", "Migrate", "Update All", "Test"
                },
            ArrayType ( "Indexed" )]
        uint16 InstallOptions[],

        [IN, Description("Installation option values"),
            ArrayType ( "Indexed" )]
        string InstallOptionValues[]
    );
};
