class RPATH_SystemSurveyService: CIM_Service {
    [Description ("Check for updates"),
       ValueMap { "0", "1", "2", "3", "4", "5", "..", "4096",
          "4097..32767",
          "32768..65535" },
       Values { "Job Completed with No Error", "Not Supported",
          "Unspecified Error", "Timeout", "Failed",
          "Invalid Parameter", "DMTF Reserved",
          "Method Parameters Checked - Job Started",
          "Method Reserved", "Vendor Specific" }]
   uint32 Scan(
         [IN, Description (
             "A list of packages against which a preview will be computed"
             )]
      String DesiredPackages[],
         [IN ( false ), OUT, Description (
             "Reference to the job (may be null if job completed)."
              )]
      CIM_ConcreteJob REF Job);
};
