[Description (
    "RPATH_Configuration class enabling configuration management.") ]
class RPATH_Configuration : CIM_SystemSetting {
    [Description (
        "Configuration value.") ]
    string Value;
    [Override ("ApplyToMSE")]
    uint32 ApplyToMSE(
         [IN, Description (
             "The ManagedSystemElement to which the Setting is being applied."
              )]
      CIM_ManagedSystemElement REF MSE,
         [IN, Description (
             "TimeToApply can be either a specific time or a time interval."
              )]
      datetime TimeToApply,
         [IN, Description (
             "The required completion time for the method." )]
      datetime MustBeCompletedBy,
         [IN( false ), OUT, Description (
             "A string array that lists log messages gathered when this "
             "method was run.") ]
      string OperationLogs[]);
};
