class RPATH_UpdateConcreteJob : CIM_ConcreteJob {
    [ Description("The results of running this job, serialized as strings") ]
    string JobResults[];

    [Description (
        "Apply an update job."),
       ValueMap { "0", "1"},
       Values { "OK", "Failed"}]
    uint16 ApplyUpdate();
};
